version: '2'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: counter
      POSTGRES_DB: viblo-counter
    ports:
      - "5432:5432"

  app:
    image: node:8
    environment:
      PGUSER: counter
      PGPASSWORD: secret
      PGDATABASE: viblo-counter
      PGHOST: db
    links:
      - db
